### ISSUE TITLE
compatibility issue with arweave app?

### ISSUE THREAD

**Issue by user0000010** [Zondax/ledger-arweave#101]
Ledger mentioned it was a compatibility issue on architecture with arweave app. do you know what issue? is it resolved? What's the current status? Since I read there is still a update on this project in recent weeks. 

Very much look forward to your answer. 

Thanks!

:link: [zboto Link](https://app.clickup.com/t/8693h9v6e)

**Comment by ftheirs** [comment]
Hi @user0000010, the issue is still present. The bluetooth module times out when generating the p and q values. This should be handled at OS level, there is not much we can do from the app code to fix it 😞
