### ISSUE TITLE
Merging to LedgerHQ/app-arweave is blocked, why don't you fix the merging issue, plz resolve the issue, so people can use passphrases

### ISSUE THREAD

**Issue by user0000010** [Zondax/ledger-arweave#102]
https://github.com/LedgerHQ/app-arweave/pull/17 

<img width="635" alt="image" src="https://github.com/Zondax/ledger-arweave/assets/109344266/8072a71c-ee41-4b69-b4fe-2d78bcc06809">

:link: [zboto Link](https://app.clickup.com/t/8693rjgt6)

**Comment by ainhoa-a** [comment]
There is no merging issue, the upgrade is currently waiting to be audited. We expect this to be completed soon so that Ledger can merge the changes.

**Comment by user0000010** [comment]
Thanks for your reply very much. Very look forward to ledger support upgrade! Community holders all want this very much!
