### ISSUE TITLE
Fix sign/transfer test on zemu

### ISSUE THREAD

**Issue by emmanuelm41** [Zondax/ledger-arweave#57]
It is not working right now. It is not running the signing algorithm. It is only taking screenshoots and comparing them.

**Comment by ainhoa-a** [comment]
@emmanuelm41  is this still relevant? This issue should already be fixed. Please check latest release.

**Comment by ftheirs** [comment]
Cryptographic functions take a really LONG time to be executed in Zemu. We will update Zemu test to run this in CI but it is working if you wait long enough
