### ISSUE TITLE
Ledger app derives same Arweave address regardless of the use of a Passphrase derivation

### ISSUE THREAD

**Issue by JohnZettler** [Zondax/ledger-arweave#95]
Hello team — passing along this feedback from my experience using a Ledger (Nano S+) to store AR tokens in cold storage.  

**Key question causing confusion**: why does the Ledger app derive the same Arweave address regardless of whether I use my passphrase derivation?

**Context**: A customer can have 2 PINs to unlock his/her Ledger. The 1st PIN reflects a 24-word seed private key and derives "honeypot addresses" on Ethereum, Bitcoin, and Solana. The 2nd PIN reflects a 24+1 — seed AND [passphrase](https://www.ledger.com/academy/passphrase-an-advanced-security-feature) — private key to be used as primary addresses. This  more-secure key generation method is not unique to Ledger; GridPlus allows the same, for example. 

**Confusion**: For every chain I've used, the different private keys create a different set of addresses.  However, on Arweave (using [arweave.app](http://arweave.app/)), I always get the same address.  This is the case whether I click the "Connect with Ledger" button or the "Verify address" button in the web UI.  I always see the same Arweave address.  

Is there perhaps a bug in the Ledger implementation that is restricting the app from ingesting all the entropy?   If so, I would classify this as a high-priority security concern since users have separate trust assumptions for 24 word vs. 25 word (passphrase) wallets. 

Per `@jfbeats` in "arweave.app wallet" Discord: "my guess is that the base key is generated once and saved while the passphrase variations don't trigger a regeneration"

:link: [zboto Link](https://app.clickup.com/t/8692xz1ny)

**Comment by ftheirs** [comment]
Hi @JohnZettler! This issue was fixed since release **v1.0.20** but there is no Ledger oficial release yet. We'll try to push this asap! An updated version with latest SDK can be found [here](https://github.com/Zondax/ledger-arweave/releases/tag/v1.0.21)
