### ISSUE TITLE
RSA exponent incorrect in comment

### ISSUE THREAD

**Issue by pspacek** [Zondax/ledger-arweave#98]
Comment here is incorrect:

https://github.com/Zondax/ledger-arweave/blame/1ff63e4ba8e286b5439a88cc61e5cd0ed76c33f9/app/src/crypto_store.c#L289

0x10001 != 65337

:link: [zboto Link](https://app.clickup.com/t/8693a9tgw)

**Comment by ftheirs** [comment]
Fixed! 😄
